#!/usr/bin/env sh

# get a random joke from reddtt /r/jokes
joke() {
	ruby -rjson -rrestclient -e "j = JSON.parse(RestClient.get('https://www.reddit.com/r/jokes/random/.json'))[0]['data']['children'][0]['data'];
	p j['title'], j['selftext']"
}

# start webserver for current directory (ruby)
rws() { port="${1:-8000}"; ruby -run -e httpd . -p $port; }

# start webserver for current directory (python)
pws() { python -m SimpleHTTPServer; }

# colorful man page
man() {
	env \
		LESS_TERMCAP_mb=$(printf "\e[1;31m") \
		LESS_TERMCAP_md=$(printf "\e[1;31m") \
		LESS_TERMCAP_me=$(printf "\e[0m") \
		LESS_TERMCAP_se=$(printf "\e[0m") \
		LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
		LESS_TERMCAP_ue=$(printf "\e[0m") \
		LESS_TERMCAP_us=$(printf "\e[1;32m") \
		man "$@"
}

# Shell colors and formatting
# Colors: [Black Red Green Yellow Blue Purple Cyan White]
# ANSI Escape Code	attribute
# 0									Reset / Normal	all attributes off
# 1									Bold or increased intensity
# 2									Faint (decreased intensity)
# 3									Italic
# 4									Underline
# 5									Blink: Slow
# 6									Blink: Rapid
# 7									Image: Negative	inverse or reverse
# 30–37							Set text color (foreground)
# 39								Default text color (foreground)
# 40–47							Set background color
# 49								Default background color
# 90–97							Set foreground text color, high intensity
# 100–107						Set background color, high intensity
clf() {
	for bg in {40..47} 49 {100..107} ; do
		for fg in {30..37} 39 {90..97} ; do
			for attr in {0..7} ; do
				echo "\033[${attr};${bg};${fg}m This is: [${attr};${bg};${fg}m \033[0m"
			done
		done
	done
}
