#!/usr/bin/env sh

# Load RVM into a shell session *as a function*
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

# Load dotfiles
[[ -s $HOME/dotfiles/shell/env ]] && source $HOME/dotfiles/shell/env
[[ -s $HOME/dotfiles/shell/aliases ]] && source $HOME/dotfiles/shell/aliases
[[ -s $HOME/dotfiles/shell/functions ]] && source $HOME/dotfiles/shell/functions

# load brew formula
[[ -s $(brew --prefix)/etc/profile.d/z.sh ]] && source $(brew --prefix)/etc/profile.d/z.sh
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && source $(brew --prefix)/etc/profile.d/autojump.sh

# oh-my-zsh configuration.
[[ -d $HOME/.oh-my-zsh ]] && export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="agnoster"

plugins+=(git git-prompt history history-substring-search k osx rvm sublime)
plugins+=(themes z zsh-completions zsh-syntax-highlighting zsh-autosuggestions zsh-history-substring-search)

ZSH_HIGHLIGHT_HIGHLIGHTERS+=(main brackets pattern cursor)
AUTOSUGGESTION_HIGHLIGHT_COLOR='fg=8'
AUTOSUGGESTION_HIGHLIGHT_CURSOR=0
AUTOSUGGESTION_ACCEPT_RIGHT_ARROW=1

source ${ZSH}/oh-my-zsh.sh

autoload -U compinit && compinit
zle-line-init() {
    zle autosuggest-start
}
zle -N zle-line-init